config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'admin_panel'

  devise_for :users, only: :omniauth_callbacks, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  scope '(:locale)', locale: /en/ do
    root 'store#index'

    get 'store', to: 'store#store'
    get 'error', to: 'store#error'

    resource :cart, only: %i(show update) do
      delete 'empty'
    end

    resources :books, only: :show do
      resource :review, only: %i(new create)
      post 'order', to: 'order_items#create'
    end

    resources :authors, only: %i(show)
    resources :categories, only: %i(show)
    resources :addresses, only: %i(create update)
    resources :checkout, only: %i(index show update)

    resources :orders, only: %i(index show) do
      resources :order_items, path: 'item', as: :item, only: %i(create destroy)
    end

    match 'settings', to: 'settings#index', via: %i(get post patch), as: 'settings'

    devise_for :users, skip: :omniauth_callbacks, path_names: {
      sign_in: 'sign-in',
      sign_up: 'sign-up',
      sign_out: 'sign-out'
    }, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
    }
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true
class ApplicationController < ActionController::Base
  include Rectify::ControllerHelpers

  include Localization
  include Adminization
  include Authentication

  protect_from_forgery with: :exception

  private

  def default_url_options
    { locale: I18n.locale }
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true
module ApplicationHelper
  def paginate(objects, options = {})
    options.reverse_merge! ({
      theme: 'twitter-bootstrap-3'
    })

    super objects, options
  end
end

app/views/application/_header.html.haml
.header
  %nav.navbar.navbar-default
    .navbar-header
      %button.navbar-toggle.collapsed(aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" type="button")
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar

      = link_to 'The Bookstore', root_path, class: 'navbar-brand'

    #navbar.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right.text-center
        %li= link_to t('.nav.home'), root_path
        %li= link_to t('.nav.store'), store_path
        %li= link_to t('.nav.cart'), cart_path

        - if current_user

          %li= link_to t('.nav.orders'), orders_path
          %li= link_to t('.nav.settings'), settings_path
          %li= link_to t('.nav.logout'), destroy_user_session_path, method: :delete

        - else

          %li= link_to t('.nav.signin'), new_user_session_path

app/views/application/_notice.html.haml
- if flash[:notice]
  .alert.alert-info
    = flash[:notice]